package net.anotheria.anodoc.service;

/**
 * File:ModuleStorageFactory
 * Generated by CIPEnhancer V1.0.
 * Factory for the stub.
 * NEVER change generated code if you don't know what you do.
 *
 * @author another
 * @version $Id: $Id
 */
public class ModuleStorageFactory{

	private ModuleStorageFactory() {
	}

	/**
	 * <p>getModuleStorage.</p>
	 *
	 * @return a {@link net.anotheria.anodoc.service.IModuleStorage} object.
	 */
	public static final IModuleStorage getModuleStorage(){
//		return new ModuleStorageC();
		return null;
	}
}
