<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>net.anotheria</groupId>
        <artifactId>ano-doc-build</artifactId>
        <version>5.0.7-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>ano-doc</artifactId>
	<name>anotheria.net document and site generation framework</name>


<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>ano-util</artifactId>
			<version>${ano-util.version}</version>
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>configureme</artifactId>
			<version>${configureme.version}</version>
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>moskito-core</artifactId>
			<version>${moskito.version}</version>
		</dependency>
    <dependency>
        <groupId>net.anotheria</groupId>
        <artifactId>moskito-aop</artifactId>
        <version>${moskito.version}</version>
    </dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>moskito-web</artifactId>
			<version>${moskito.version}</version>
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>ano-maf</artifactId>
			<version>${ano-maf.version}</version>
			<exclusions>
				<exclusion>  
		          <groupId>net.anotheria</groupId>
		          <artifactId>ano-prise</artifactId>
		        </exclusion>
				<exclusion>  
		          <groupId>blowfish</groupId>
		          <artifactId>blowfish</artifactId>
		        </exclusion>
			</exclusions>
			
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>ano-plass</artifactId>
			<version>${ano-plass.version}</version>
			<exclusions>
				<exclusion>  
		          <groupId>net.anotheria</groupId>
		          <artifactId>ano-maf</artifactId>
		        </exclusion>
				<exclusion>  
		          <groupId>blowfish</groupId>
		          <artifactId>blowfish</artifactId>
		        </exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.anotheria</groupId>
			<artifactId>ano-prise</artifactId>
			<version>${ano-prise.version}</version>
			<exclusions>
				<exclusion>  
		          <groupId>net.anotheria</groupId>
		          <artifactId>ano-maf</artifactId>
		        </exclusion>
				<exclusion>  
		          <groupId>blowfish</groupId>
		          <artifactId>blowfish</artifactId>
		        </exclusion>
			</exclusions>
			
		</dependency>
		<dependency>
			<groupId>org.jdom</groupId>
			<artifactId>jdom2</artifactId>
			<version>${jdom.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>${aws-java-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>${aws-java-sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.31</version>
        </dependency>
	</dependencies>
</project>
