package net.anotheria.asg.generator.view.jsp;

import net.anotheria.asg.generator.Context;
import net.anotheria.asg.generator.FileEntry;
import net.anotheria.asg.generator.GeneratedJSPFile;
import net.anotheria.asg.generator.GeneratorDataRegistry;
import net.anotheria.asg.generator.meta.MetaModule;

/**
 * <p>LocalizationBundleImportJspGenerator class.</p>
 *
 * @author another
 * @version $Id: $Id
 */
public class LocalizationBundleImportJspGenerator extends AbstractJSPGenerator {

    /**
     * <p>generate.</p>
     *
     * @param context a {@link Context} object.
     * @return a {@link FileEntry} object.
     */
    public FileEntry generate(Context context) {
        FileEntry page = new FileEntry(getLocalizationBundleImportPathJSP(), getLocalizationBundleImportJspName(),
                generateLocalizationBundleImportPage().createFileContent());
        page.setType(".jsp");
        return page;
    }

    /**
     * <p>getLocalizationBundleImportJspName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleImportJspName() {
        return "LocalizationBundleImport";
    }

    /**
     * <p>getSharedJspFooterPageName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getSharedJspFooterPageName() {
        return getLocalizationBundleImportJspName() + ".jsp";
    }

    /**
     * <p>getLocalizationBundleImportJspFullName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleImportJspFullName() {
        return getLocalizationBundleImportJspPath() + "/" + getSharedJspFooterPageName();
    }


    /**
     * <p>getLocalizationBundleImportPathJSP.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleImportPathJSP() {
        return FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED) + ".jsp");
    }

    /**
     * <p>getLocalizationBundleImportJspPath.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleImportJspPath() {

        return FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED)).substring(FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED)).indexOf('/')) + "/jsp";
    }

    private GeneratedJSPFile generateLocalizationBundleImportPage() {
        GeneratedJSPFile jsp = new GeneratedJSPFile();
        startNewJob(jsp);
        jsp.setName(getLocalizationBundleImportJspName());

        resetIdent();

        append(getBaseJSPHeader());

        appendString("<!--  generated by LocalizationBundleImportJspGenerator.generateLocalizationBundleImportPage -->");
        appendString("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
        appendString("<head>");
        increaseIdent();
        appendString("<title>" + getLocalizationBundleImportJspName() + "</title>");
        generatePragmas();
        appendString("<script type=\"text/javascript\" src=\"" + getCurrentJSPath("jquery-1.8.2.js") + "\"></script>");
        appendString("<script type=\"text/javascript\" src=\"" + getCurrentJSPath("anofunctions.js") + "\"></script>");
        appendString("<link href=\"" + getCurrentCSSPath("newadmin.css") + "\" rel=\"stylesheet\" type=\"text/css\">");
        decreaseIdent();
        appendString("</head>");
        appendString("<body>");

        appendString("<jsp:include page=\"" + "../../shared/jsp/" + MenuJspGenerator.getMenuPageName() + "\" flush=\"true\"/>");
        appendString("<div class=\"right\">");
        increaseIdent();
        appendString("<div class=\"r_w\">");
        increaseIdent();
        appendString("<div class=\"main_area\">");
        increaseIdent();
        appendString("<div class=\"c_l\"><!-- --></div>");
        appendString("<div class=\"c_r\"><!-- --></div>");
        appendString("<div class=\"c_b_l\"><!-- --></div>");
        appendString("<div class=\"c_b_r\"><!-- --></div>");

        increaseIdent();
        appendString("<form method=\"post\" id=\"uploadLocalization\" enctype=\"multipart/form-data\"\n>");
        appendString("<input type=\"file\" name=\"file\" />\n");
        appendString("<select name=\"locale\" class=\"locale\">");
        appendString("<ano:iterate name=\"languages\" type=\"java.lang.String\" id=\"option\">");
        appendString("<option value=\"<ano:write name=\"option\"/>\" <ano:equal name=\"option\" value=\"${selectedLanguage}\">selected</ano:equal>><ano:write name=\"option\"/></option>");
        appendString("</ano:iterate>");
        appendString("</select>");
        appendString("<input type=\"submit\" class=\"import-txt\" value=\"Import\" style=\"padding-left: 5px;padding-right: 5px;\"/>");
        appendString("</form>");

        decreaseIdent();
        appendString("<div class=\"clear\"><!-- --></div>");
        appendString("</div>");
        appendString("</div>");
        appendString("</div>");

        appendString("</body>");
        appendString("</html>");
        appendString("<script type=\"text/javascript\">");

        appendString("$(\".import-txt\").click(function (event) {\n" +
                "        event.preventDefault();\n" +
                "        var form = $('#uploadLocalization')[0];\n" +
                "        var data = new FormData(form);\n" +
                "        $.ajax({\n" +
                "            type: \"POST\",\n" +
                "            enctype: 'multipart/form-data',\n" +
                "            url: \"/ImportLocalizationBundle\",\n" +
                "            data: data,\n" +
                "            processData: false,\n" +
                "            contentType: false,\n" +
                "            success: function (data) {\n" +
                "                alert(\"Localization imported\");\n" +
                "                console.log(\"SUCCESS : \", data);\n" +
                "            },\n" +
                "            error: function (e) {\n" +
                "                alert(\"ERROR : \" + e);\n" +
                "                console.log(\"ERROR : \", e);\n" +
                "            }\n" +
                "        });\n" +
                "    });");
        appendString("</script>");
        appendString("<!-- / generated by LocalizationBundleImportJspGenerator.generateLocalizationBundleImportPage -->");

        append(getBaseJSPFooter());

        return jsp;
    }

}
