package net.anotheria.asg.generator.view.jsp;

import net.anotheria.asg.generator.Context;
import net.anotheria.asg.generator.FileEntry;
import net.anotheria.asg.generator.GeneratedJSPFile;
import net.anotheria.asg.generator.GeneratorDataRegistry;
import net.anotheria.asg.generator.meta.MetaModule;

/**
 * <p>LocalizationBundleExportJspGenerator class.</p>
 *
 * @author asamoilich
 * @version $Id: $Id
 */
public class LocalizationBundleExportJspGenerator extends AbstractJSPGenerator {

    /**
     * <p>generate.</p>
     *
     * @param context a {@link Context} object.
     * @return a {@link FileEntry} object.
     */
    public FileEntry generate(Context context) {
        FileEntry page = new FileEntry(getLocalizationBundleExportPathJSP(), getLocalizationBundleExportJspName(),
                generateLocalizationBundleExportPage().createFileContent());
        page.setType(".jsp");
        return page;
    }

    /**
     * <p>getLocalizationBundleExportJspName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleExportJspName() {
        return "LocalizationBundleExport";
    }

    /**
     * <p>getSharedJspFooterPageName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getSharedJspFooterPageName() {
        return getLocalizationBundleExportJspName() + ".jsp";
    }

    /**
     * <p>getLocalizationBundleExportJspFullName.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleExportJspFullName() {
        return getLocalizationBundleExportJspPath() + "/" + getSharedJspFooterPageName();
    }


    /**
     * <p>getLocalizationBundleExportPathJSP.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleExportPathJSP() {
        return FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED) + ".jsp");
    }

    /**
     * <p>getLocalizationBundleExportJspPath.</p>
     *
     * @return a {@link String} object.
     */
    public static final String getLocalizationBundleExportJspPath() {

        return FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED)).substring(FileEntry.package2fullPath(GeneratorDataRegistry.getInstance().getContext().getPackageName(MetaModule.SHARED)).indexOf('/')) + "/jsp";
    }

    private GeneratedJSPFile generateLocalizationBundleExportPage() {
        GeneratedJSPFile jsp = new GeneratedJSPFile();
        startNewJob(jsp);
        jsp.setName(getLocalizationBundleExportJspName());

        resetIdent();

        append(getBaseJSPHeader());

        appendString("<!--  generated by LocalizationBundleExportJspGenerator.generateLocalizationBundleExportPage -->");
        appendString("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
        appendString("<head>");
        increaseIdent();
        appendString("<title>" + getLocalizationBundleExportJspName() + "</title>");
        generatePragmas();
        appendString("<script type=\"text/javascript\" src=\"" + getCurrentJSPath("jquery-1.4.min.js") + "\"></script>");
        appendString("<script type=\"text/javascript\" src=\"" + getCurrentJSPath("anofunctions.js") + "\"></script>");
        appendString("<link href=\"" + getCurrentCSSPath("newadmin.css") + "\" rel=\"stylesheet\" type=\"text/css\">");
        decreaseIdent();
        appendString("</head>");
        appendString("<body>");

        appendString("<jsp:include page=\"" + "../../shared/jsp/" + MenuJspGenerator.getMenuPageName() + "\" flush=\"true\"/>");
        appendString("<div class=\"right\">");
        increaseIdent();
        appendString("<div class=\"r_w\">");
        increaseIdent();
        appendString("<div class=\"main_area\">");
        increaseIdent();
        appendString("<div class=\"c_l\"><!-- --></div>");
        appendString("<div class=\"c_r\"><!-- --></div>");
        appendString("<div class=\"c_b_l\"><!-- --></div>");
        appendString("<div class=\"c_b_r\"><!-- --></div>");

        increaseIdent();
        appendString("<select name=\"language\" class=\"locale\">");
        appendString("<ano:iterate name=\"languages\" type=\"java.lang.String\" id=\"option\">");
        appendString("<option value=\"<ano:write name=\"option\"/>\" <ano:equal name=\"option\" value=\"${selectedLanguage}\">selected</ano:equal>><ano:write name=\"option\"/></option>");
        appendString("</ano:iterate>");
        appendString("</select>");
        appendString("<a href=\"#\" class=\"button export-txt\"><span>Export</span></a>");
        decreaseIdent();
        appendString("<div class=\"clear\"><!-- --></div>");
        appendString("</div>");
        appendString("</div>");
        appendString("</div>");

        appendString("</body>");
        appendString("</html>");
        appendString("<script type=\"text/javascript\">");
        appendString("$('.export-txt').click( function(event) {\n" +
                "        event.preventDefault();\n" +
                "        event.stopPropagation();\n" +
                "\n" +
                "        var locale = $('.locale').val();\n" +
                "        var data = {\n" +
                "            locale: locale\n" +
                "        };\n" +
                "        let fileNameDate = new Date().toISOString().replace(\"T\",\"_\").substring(0, 19).replaceAll(\":\",\"_\");\n" +
                "        $.ajax({\n" +
                "            url: 'exportLocalizationBundlesToTxt',\n" +
                "            data: data,\n" +
                "            success: function (data) {\n" +
                "                var element = document.createElement('a');\n" +
                "                element.setAttribute('href', 'data:attachment/txt;charset=utf-8,' + encodeURIComponent(data));\n" +
                "                element.setAttribute('download', fileNameDate + '_bundles_export_' + locale + '.txt');\n" +
                "\n" +
                "                element.style.display = 'none';\n" +
                "                document.body.appendChild(element);\n" +
                "                element.click();\n" +
                "                document.body.removeChild(element);\n" +
                "            }\n" +
                "        });\n" +
                "    });");
        appendString("</script>");
        appendString("<!-- / generated by LocalizationBundleExportJspGenerator.generateLocalizationBundleExportPage -->");

        append(getBaseJSPFooter());

        return jsp;
    }

}
